### ISSUE TITLE
App display an image if I drag an image file

### ISSUE THREAD

**Issue by firestar300** [n457/Uncolored#15]
Hi,

I checked a current problem due to Electron. If i drag an image file on the Uncolored App, the window display the image and i can't return to the main app system. I have to quit and restart Uncolored. Do you think you can disable it or just display the image on the WYSIWYG editor on dragging ?

**Comment by n457** [comment]
Hi,
This issue **was solved in version 0.8.1**, please update (Un)colored ;)
https://n457.github.io/Uncolored/

**Comment by n457** [comment]
Duplicate of https://github.com/n457/Uncolored/issues/5
