### ISSUE TITLE
Add custom line spacing

### ISSUE THREAD

**Issue by kenziesimpson** [n457/Uncolored#16]
I use uncolored to record my translations of classic poems, and I really like the look of the editor, however there is an issue in my use case; when I press enter to include another line in the same stanza, it is double spaced. Preferably, there would be a way to add a new line without adding extra space, as if the editor were just wrapping down from the previous line being too long. Maybe `alt+enter` as the keybind?

**Comment by n457** [comment]
Hi @msimp19, it make sense, I've done it.
It will be available in the next release via `shift+enter` (which is a standard shortcut for that)

**Comment by kenziesimpson** [comment]
Sounds good, thanks!

**Comment by n457** [comment]
👍
