### ISSUE TITLE
Draggability on windows

### ISSUE THREAD

**Issue by ghost** [n457/Uncolored#17]
(Don't know if that's a word...)

When I have Uc on AlwaysOnTop mode, I obviously want to reduce it in size for taking notes, right? Well, when the window size is reduced, half of the screen is small buttons, and there is nowhere to grip the window to drag it around...

I know this would be a lot of work to fix, but implementing a form of responsive design for Uc would help quite a bit while taking notes on Uc.

Thanks.

**Comment by n457** [comment]
Hi @codesharkasm,

I invistigated a while on this issue and the cause of this **is ridiculous** : by default, the toolbar is **transparent and above the window draggable region**. It prevent as well the draggability of this region, and in the case of a small window, **the whole draggable region**...

I will fix this **ASAP** and release a v.0.10.2
Thanks a lot for the feedback

**Comment by n457** [comment]
Oh, this issue **is also caused by tabs**, they prevent as well the draggability of the window draggable region.

**Comment by n457** [comment]
**Issue fixed** & updated title bar with **responsive for small (Un)colored window**.
OK in **next 0.10.2 release**.

**Comment by ghost** [comment]
@n457 Thanks!
