### ISSUE TITLE
Scale to size imported media

### ISSUE THREAD

**Issue by Togora** [n457/Uncolored#29]
Hi,

My suggestion is to provide the ability to scale to size all types of media be that images, video, web pages, etc. I don't know if this is already possible but I couldn't see how it can be done at present.

Great program by the way.

**Comment by rafifos** [comment]
(Un)colored is being rewritten from scratch. Please wait for the new version, we will probably not see any development on the actual version anymore

**Comment by n457** [comment]
Hi @Togora & @h4ndshake !
The size of **all elements** in (Un)colored and in exported documents are handled **by themes** (**UI themes** in the first case, and **documents themes** in the 2nd case).
So no, you **will not** be able to resize elements manually, and **it's totally intentionnal** (that's the point of themes) ;)

Thank you both for contributing, it's a pleasure :)
