### ISSUE TITLE
Window title bar controls integration in UI

### ISSUE THREAD

**Issue by ghost** [n457/Uncolored#3]
@n457 As I said in my first issue, I love Uncolored. However, to fully complete the UI, on Windows could you integrate the window controls into the UI? 

![image](https://cloud.githubusercontent.com/assets/8107485/18804807/30ce448e-81ce-11e6-9649-deebcd8789b8.png)

Which do you think looks better? (The one on the left is [Typora](http://typora.io). )

The style on the left can be done by inserting `frame: false,` into your electron `main.js` and making `close`, `minimize`, and `maximize` window controls in the html.

It just looks much cleaner and "native".

**Comment by n457** [comment]
Hi @codesharkasm, **I'm very glad you love the app** :)

**I totally agree with you**, frame integrated window controls looks much cleaner and **allow more design possibilities**.

The integrated window controls **were implemented in the early (and private) versions** of (Un)colored, but **this has raised kind of an issue**.
What if the user **has an external program to add/edit/remove controls/actions** in applications window bars ? I'm guessing, with no window frame, such external programs cannot work (I haven't tested yet).

I was tempted do do that at the time and I'm still am. I will very probably integrate the window controls into the UI **in next versions** though

Stick with us for future (Un)colored enhancements ! ;)

**Comment by n457** [comment]
Integrated window controls are coming in (Un)colored next release 🎉 

![no-frame-linux](https://cloud.githubusercontent.com/assets/11824581/19152533/b403971a-8bd2-11e6-95f1-c365e0fdc445.png)
![no-frame-linux-settings](https://cloud.githubusercontent.com/assets/11824581/19152532/b4022c54-8bd2-11e6-9040-b8e9e798000e.png)
![no-frame-osx](https://cloud.githubusercontent.com/assets/11824581/19152534/b4091244-8bd2-11e6-858d-e5fcc915e173.png)
![no-frame-win](https://cloud.githubusercontent.com/assets/11824581/19152535/b4091582-8bd2-11e6-986b-cc22d0ec4342.png)

**Comment by ghost** [comment]
@n457 Love the Win10 one! Thanks!
